"""Alembic迁移脚本模板

每次使用 alembic revision 命令时会使用此模板
Pylint模板变量：rev, down_revision, branch_labels, depends_on
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76fb9b2d9535'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """升级数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('department', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('department', 'dept_code',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='系部编码',
               existing_nullable=False)
    op.alter_column('department', 'name',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='系部名称',
               existing_nullable=False)
    op.alter_column('department', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               comment=None,
               existing_comment='1=启用,0=停用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('department', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3)'))
    op.alter_column('department', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'))
    op.drop_table_comment(
        'department',
        existing_comment='系部',
        schema=None
    )
    op.alter_column('major', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('major', 'department_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='所属系部ID',
               existing_nullable=False)
    op.alter_column('major', 'major_code',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='专业编码',
               existing_nullable=False)
    op.alter_column('major', 'name',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='专业名称',
               existing_nullable=False)
    op.alter_column('major', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               comment=None,
               existing_comment='1=启用,0=停用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('major', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3)'))
    op.alter_column('major', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'))
    op.drop_constraint(op.f('fk_major_department'), 'major', type_='foreignkey')
    op.create_foreign_key(None, 'major', 'department', ['department_id'], ['id'])
    op.drop_table_comment(
        'major',
        existing_comment='专业',
        schema=None
    )
    op.add_column('operation_log', sa.Column('user_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='操作用户ID'))
    op.add_column('operation_log', sa.Column('resource_type', sa.String(length=64), nullable=False, comment='资源类型: topic/paper/user'))
    op.add_column('operation_log', sa.Column('resource_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='资源ID'))
    op.add_column('operation_log', sa.Column('ip_address', sa.String(length=64), nullable=True, comment='IP地址'))
    op.alter_column('operation_log', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('operation_log', 'action',
               existing_type=mysql.VARCHAR(length=64),
               comment='操作类型: CREATE/UPDATE/DELETE',
               existing_comment='动作标识',
               existing_nullable=False)
    op.alter_column('operation_log', 'detail',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               comment='操作详情JSON',
               existing_comment='详情(JSON)',
               existing_nullable=True)
    op.alter_column('operation_log', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3)'))
    op.drop_index(op.f('idx_log_actor'), table_name='operation_log')
    op.drop_constraint(op.f('fk_log_actor'), 'operation_log', type_='foreignkey')
    op.create_foreign_key(None, 'operation_log', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.drop_table_comment(
        'operation_log',
        existing_comment='操作日志',
        schema=None
    )
    op.drop_column('operation_log', 'target_table')
    op.drop_column('operation_log', 'target_id')
    op.drop_column('operation_log', 'actor_id')
    op.drop_column('operation_log', 'ip')
    op.alter_column('paper', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('paper', 'student_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='学生ID',
               existing_comment='学生用户ID',
               existing_nullable=False)
    op.alter_column('paper', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.String(length=16),
               comment='状态: DRAFT/SUBMITTED/REVIEWED/APPROVED/REJECTED',
               existing_comment='0=编辑中,1=已提交,2=评审中,3=待修改,4=通过,5=归档',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('idx_paper_status'), table_name='paper')
    op.drop_index(op.f('idx_paper_topic'), table_name='paper')
    op.drop_index(op.f('uq_paper_student_term'), table_name='paper')
    op.drop_constraint(op.f('fk_paper_topic'), 'paper', type_='foreignkey')
    op.drop_constraint(op.f('fk_paper_student'), 'paper', type_='foreignkey')
    op.create_foreign_key(None, 'paper', 'topic', ['topic_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'paper', 'user', ['student_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_table_comment(
        'paper',
        existing_comment='论文',
        schema=None
    )
    op.drop_column('paper', 'submitted_at')
    op.drop_column('paper', 'archived_at')
    op.drop_column('paper', 'term')
    op.drop_column('paper', 'abstract')
    op.drop_column('paper', 'keywords')
    op.drop_column('paper', 'academic_year')
    op.add_column('paper_attachment', sa.Column('paper_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='论文ID'))
    op.add_column('paper_attachment', sa.Column('filename', sa.String(length=255), nullable=False, comment='文件名'))
    op.add_column('paper_attachment', sa.Column('attachment_type', sa.String(length=32), nullable=False, comment='附件类型: proposal/reference/other'))
    op.alter_column('paper_attachment', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('paper_attachment', 'storage_url',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.String(length=512),
               comment='存储路径',
               existing_comment='存储地址/URL',
               existing_nullable=False)
    op.alter_column('paper_attachment', 'file_size',
               existing_type=mysql.BIGINT(unsigned=True),
               type_=sa.Integer(),
               comment='文件大小(字节)',
               existing_comment='文件大小字节',
               existing_nullable=False)
    op.alter_column('paper_attachment', 'file_hash',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=64),
               nullable=False,
               comment='文件哈希值',
               existing_comment='文件哈希(SHA256)')
    op.drop_index(op.f('idx_att_version'), table_name='paper_attachment')
    op.drop_constraint(op.f('fk_att_version'), 'paper_attachment', type_='foreignkey')
    op.drop_constraint(op.f('fk_att_uploader'), 'paper_attachment', type_='foreignkey')
    op.create_foreign_key(None, 'paper_attachment', 'paper', ['paper_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_table_comment(
        'paper_attachment',
        existing_comment='论文版本附件',
        schema=None
    )
    op.drop_column('paper_attachment', 'uploaded_by')
    op.drop_column('paper_attachment', 'mime_type')
    op.drop_column('paper_attachment', 'file_name')
    op.drop_column('paper_attachment', 'paper_version_id')
    op.add_column('paper_version', sa.Column('storage_url', sa.String(length=512), nullable=False, comment='存储路径'))
    op.add_column('paper_version', sa.Column('file_hash', sa.String(length=64), nullable=False, comment='文件哈希值'))
    op.add_column('paper_version', sa.Column('comment', sa.Text(), nullable=True, comment='版本说明'))
    op.add_column('paper_version', sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='上传时间'))
    op.alter_column('paper_version', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('paper_version', 'version_no',
               existing_type=mysql.INTEGER(),
               comment='版本号',
               existing_comment='版本序号(1开始递增)',
               existing_nullable=False)
    op.alter_column('paper_version', 'is_final',
               existing_type=mysql.TINYINT(),
               comment='是否最终版本',
               existing_comment='是否标记为最终版本',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('idx_version_paper'), table_name='paper_version')
    op.drop_index(op.f('uq_paper_version_no'), table_name='paper_version')
    op.drop_constraint(op.f('fk_version_submitter'), 'paper_version', type_='foreignkey')
    op.drop_table_comment(
        'paper_version',
        existing_comment='论文版本',
        schema=None
    )
    op.drop_column('paper_version', 'submitted_at')
    op.drop_column('paper_version', 'content_text')
    op.drop_column('paper_version', 'notes')
    op.drop_column('paper_version', 'content_format')
    op.drop_column('paper_version', 'submitted_by')
    op.alter_column('permission', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'permission',
        existing_comment='权限',
        schema=None
    )
    op.alter_column('role', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.drop_table_comment(
        'role',
        existing_comment='角色',
        schema=None
    )
    op.alter_column('role_permission', 'role_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='角色ID',
               existing_nullable=False)
    op.alter_column('role_permission', 'permission_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='权限ID',
               existing_nullable=False)
    op.drop_table_comment(
        'role_permission',
        existing_comment='角色-权限关联',
        schema=None
    )
    op.alter_column('topic', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('topic', 'title',
               existing_type=mysql.VARCHAR(length=255),
               comment='选题标题',
               existing_comment='题目标题',
               existing_nullable=False)
    op.alter_column('topic', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               nullable=False,
               comment='选题详情',
               existing_comment='题目描述')
    op.alter_column('topic', 'tutor_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='发布导师ID',
               existing_comment='导师用户ID',
               existing_nullable=False)
    op.alter_column('topic', 'major_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='所属专业ID',
               existing_comment='所属专业',
               existing_nullable=False)
    op.alter_column('topic', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.String(length=16),
               comment='状态: DRAFT/PUBLISHED/LOCKED/ARCHIVED',
               existing_comment='0=草稿,1=发布,2=锁定,3=归档',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('topic', 'max_students',
               existing_type=mysql.INTEGER(),
               comment='最大选择人数',
               existing_comment='最大可选学生数',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('topic', 'current_students',
               existing_type=mysql.INTEGER(),
               comment='当前已选人数',
               existing_comment='当前已确认学生数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.drop_index(op.f('idx_topic_major_status'), table_name='topic')
    op.drop_index(op.f('idx_topic_tutor'), table_name='topic')
    op.drop_index(op.f('idx_topic_year_term'), table_name='topic')
    op.drop_constraint(op.f('fk_topic_tutor'), 'topic', type_='foreignkey')
    op.drop_constraint(op.f('fk_topic_major'), 'topic', type_='foreignkey')
    op.create_foreign_key(None, 'topic', 'major', ['major_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'topic', 'user', ['tutor_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_table_comment(
        'topic',
        existing_comment='选题',
        schema=None
    )
    op.drop_column('topic', 'academic_year')
    op.drop_column('topic', 'term')
    op.add_column('topic_application', sa.Column('application_reason', sa.Text(), nullable=True, comment='申请理由'))
    op.add_column('topic_application', sa.Column('decision_comment', sa.Text(), nullable=True, comment='审批意见'))
    op.alter_column('topic_application', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('topic_application', 'student_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='申请学生ID',
               existing_comment='学生用户ID',
               existing_nullable=False)
    op.alter_column('topic_application', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.String(length=16),
               comment='状态: PENDING/APPROVED/REJECTED/WITHDRAWN',
               existing_comment='0=待审批,1=通过,2=拒绝,3=取消',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('topic_application', 'decision_by',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='审批人ID',
               existing_comment='审批人(导师)',
               existing_nullable=True)
    op.drop_index(op.f('idx_app_student_status'), table_name='topic_application')
    op.drop_index(op.f('idx_app_topic_status'), table_name='topic_application')
    op.drop_index(op.f('uq_app_topic_student'), table_name='topic_application')
    op.drop_constraint(op.f('fk_app_topic'), 'topic_application', type_='foreignkey')
    op.drop_constraint(op.f('fk_app_student'), 'topic_application', type_='foreignkey')
    op.drop_constraint(op.f('fk_app_decider'), 'topic_application', type_='foreignkey')
    op.create_foreign_key(None, 'topic_application', 'user', ['decision_by'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
    op.create_foreign_key(None, 'topic_application', 'topic', ['topic_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(None, 'topic_application', 'user', ['student_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_table_comment(
        'topic_application',
        existing_comment='选题申请',
        schema=None
    )
    op.drop_column('topic_application', 'remark')
    op.alter_column('user', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='登录用户名',
               existing_nullable=False)
    op.alter_column('user', 'real_name',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='真实姓名',
               existing_nullable=False)
    op.alter_column('user', 'student_no',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='学号(学生)',
               existing_nullable=True)
    op.alter_column('user', 'teacher_no',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='工号(导师)',
               existing_nullable=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='手机号',
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=128),
               comment=None,
               existing_comment='邮箱',
               existing_nullable=True)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='密码哈希',
               existing_nullable=False)
    op.alter_column('user', 'password_salt',
               existing_type=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='密码盐',
               existing_nullable=False)
    op.alter_column('user', 'department_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='所属系部（管理员可为空）',
               existing_nullable=True)
    op.alter_column('user', 'primary_major_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='主专业ID',
               existing_nullable=True)
    op.alter_column('user', 'status',
               existing_type=mysql.TINYINT(),
               type_=sa.Integer(),
               comment=None,
               existing_comment='1=正常,0=锁定',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'last_login_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment=None,
               existing_comment='最后登录时间',
               existing_nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3)'))
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'))
    op.alter_column('user', 'deleted_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment=None,
               existing_comment='软删除时间',
               existing_nullable=True)
    op.drop_index(op.f('idx_user_dept'), table_name='user')
    op.drop_index(op.f('idx_user_major'), table_name='user')
    op.drop_index(op.f('uq_user_email'), table_name='user')
    op.drop_index(op.f('uq_user_phone'), table_name='user')
    op.drop_index(op.f('uq_user_student_no'), table_name='user')
    op.drop_index(op.f('uq_user_teacher_no'), table_name='user')
    op.drop_constraint(op.f('fk_user_dept'), 'user', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_primary_major'), 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'major', ['primary_major_id'], ['id'])
    op.create_foreign_key(None, 'user', 'department', ['department_id'], ['id'])
    op.drop_table_comment(
        'user',
        existing_comment='用户',
        schema=None
    )
    op.alter_column('user_major', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_major', 'major_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='专业ID',
               existing_nullable=False)
    op.drop_table_comment(
        'user_major',
        existing_comment='用户与专业映射',
        schema=None
    )
    op.alter_column('user_role', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='用户ID',
               existing_nullable=False)
    op.alter_column('user_role', 'role_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment=None,
               existing_comment='角色ID',
               existing_nullable=False)
    op.drop_table_comment(
        'user_role',
        existing_comment='用户-角色关联',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """回滚数据库"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user_role',
        '用户-角色关联',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_role', 'role_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='角色ID',
               existing_nullable=False)
    op.alter_column('user_role', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='用户ID',
               existing_nullable=False)
    op.create_table_comment(
        'user_major',
        '用户与专业映射',
        existing_comment=None,
        schema=None
    )
    op.alter_column('user_major', 'major_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='专业ID',
               existing_nullable=False)
    op.alter_column('user_major', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='用户ID',
               existing_nullable=False)
    op.create_table_comment(
        'user',
        '用户',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_primary_major'), 'user', 'major', ['primary_major_id'], ['id'], onupdate='RESTRICT', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_user_dept'), 'user', 'department', ['department_id'], ['id'], onupdate='RESTRICT', ondelete='SET NULL')
    op.create_index(op.f('uq_user_teacher_no'), 'user', ['teacher_no'], unique=True)
    op.create_index(op.f('uq_user_student_no'), 'user', ['student_no'], unique=True)
    op.create_index(op.f('uq_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('uq_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('idx_user_major'), 'user', ['primary_major_id'], unique=False)
    op.create_index(op.f('idx_user_dept'), 'user', ['department_id'], unique=False)
    op.alter_column('user', 'deleted_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment='软删除时间',
               existing_nullable=True)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'))
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3)'))
    op.alter_column('user', 'last_login_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment='最后登录时间',
               existing_nullable=True)
    op.alter_column('user', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               comment='1=正常,0=锁定',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('user', 'primary_major_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='主专业ID',
               existing_nullable=True)
    op.alter_column('user', 'department_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='所属系部（管理员可为空）',
               existing_nullable=True)
    op.alter_column('user', 'password_salt',
               existing_type=mysql.VARCHAR(length=64),
               comment='密码盐',
               existing_nullable=False)
    op.alter_column('user', 'password_hash',
               existing_type=mysql.VARCHAR(length=255),
               comment='密码哈希',
               existing_nullable=False)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=128),
               comment='邮箱',
               existing_nullable=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=32),
               comment='手机号',
               existing_nullable=True)
    op.alter_column('user', 'teacher_no',
               existing_type=mysql.VARCHAR(length=64),
               comment='工号(导师)',
               existing_nullable=True)
    op.alter_column('user', 'student_no',
               existing_type=mysql.VARCHAR(length=64),
               comment='学号(学生)',
               existing_nullable=True)
    op.alter_column('user', 'real_name',
               existing_type=mysql.VARCHAR(length=64),
               comment='真实姓名',
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=64),
               comment='登录用户名',
               existing_nullable=False)
    op.alter_column('user', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.add_column('topic_application', sa.Column('remark', mysql.VARCHAR(length=255), nullable=True, comment='申请备注/拒绝原因'))
    op.create_table_comment(
        'topic_application',
        '选题申请',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'topic_application', type_='foreignkey')
    op.drop_constraint(None, 'topic_application', type_='foreignkey')
    op.drop_constraint(None, 'topic_application', type_='foreignkey')
    op.create_foreign_key(op.f('fk_app_decider'), 'topic_application', 'user', ['decision_by'], ['id'], onupdate='RESTRICT', ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_app_student'), 'topic_application', 'user', ['student_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_app_topic'), 'topic_application', 'topic', ['topic_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('uq_app_topic_student'), 'topic_application', ['topic_id', 'student_id'], unique=True)
    op.create_index(op.f('idx_app_topic_status'), 'topic_application', ['topic_id', 'status'], unique=False)
    op.create_index(op.f('idx_app_student_status'), 'topic_application', ['student_id', 'status'], unique=False)
    op.alter_column('topic_application', 'decision_by',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='审批人(导师)',
               existing_comment='审批人ID',
               existing_nullable=True)
    op.alter_column('topic_application', 'status',
               existing_type=sa.String(length=16),
               type_=mysql.TINYINT(),
               comment='0=待审批,1=通过,2=拒绝,3=取消',
               existing_comment='状态: PENDING/APPROVED/REJECTED/WITHDRAWN',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('topic_application', 'student_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='学生用户ID',
               existing_comment='申请学生ID',
               existing_nullable=False)
    op.alter_column('topic_application', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('topic_application', 'decision_comment')
    op.drop_column('topic_application', 'application_reason')
    op.add_column('topic', sa.Column('term', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='学期:1=上,2=下'))
    op.add_column('topic', sa.Column('academic_year', mysql.VARCHAR(length=16), nullable=False, comment='学年: 2024-2025'))
    op.create_table_comment(
        'topic',
        '选题',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.create_foreign_key(op.f('fk_topic_major'), 'topic', 'major', ['major_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_topic_tutor'), 'topic', 'user', ['tutor_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_index(op.f('idx_topic_year_term'), 'topic', ['academic_year', 'term'], unique=False)
    op.create_index(op.f('idx_topic_tutor'), 'topic', ['tutor_id'], unique=False)
    op.create_index(op.f('idx_topic_major_status'), 'topic', ['major_id', 'status'], unique=False)
    op.alter_column('topic', 'current_students',
               existing_type=mysql.INTEGER(),
               comment='当前已确认学生数',
               existing_comment='当前已选人数',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('topic', 'max_students',
               existing_type=mysql.INTEGER(),
               comment='最大可选学生数',
               existing_comment='最大选择人数',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('topic', 'status',
               existing_type=sa.String(length=16),
               type_=mysql.TINYINT(),
               comment='0=草稿,1=发布,2=锁定,3=归档',
               existing_comment='状态: DRAFT/PUBLISHED/LOCKED/ARCHIVED',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('topic', 'major_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='所属专业',
               existing_comment='所属专业ID',
               existing_nullable=False)
    op.alter_column('topic', 'tutor_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='导师用户ID',
               existing_comment='发布导师ID',
               existing_nullable=False)
    op.alter_column('topic', 'description',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               nullable=True,
               comment='题目描述',
               existing_comment='选题详情')
    op.alter_column('topic', 'title',
               existing_type=mysql.VARCHAR(length=255),
               comment='题目标题',
               existing_comment='选题标题',
               existing_nullable=False)
    op.alter_column('topic', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'role_permission',
        '角色-权限关联',
        existing_comment=None,
        schema=None
    )
    op.alter_column('role_permission', 'permission_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='权限ID',
               existing_nullable=False)
    op.alter_column('role_permission', 'role_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='角色ID',
               existing_nullable=False)
    op.create_table_comment(
        'role',
        '角色',
        existing_comment=None,
        schema=None
    )
    op.alter_column('role', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'permission',
        '权限',
        existing_comment=None,
        schema=None
    )
    op.alter_column('permission', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.add_column('paper_version', sa.Column('submitted_by', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='提交人ID'))
    op.add_column('paper_version', sa.Column('content_format', mysql.TINYINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='0=无,1=markdown,2=html,3=text'))
    op.add_column('paper_version', sa.Column('notes', mysql.VARCHAR(length=255), nullable=True, comment='备注'))
    op.add_column('paper_version', sa.Column('content_text', mysql.MEDIUMTEXT(), nullable=True, comment='正文内容(可选)'))
    op.add_column('paper_version', sa.Column('submitted_at', mysql.DATETIME(fsp=3), server_default=sa.text('CURRENT_TIMESTAMP(3)'), nullable=False, comment='提交时间'))
    op.create_table_comment(
        'paper_version',
        '论文版本',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('fk_version_submitter'), 'paper_version', 'user', ['submitted_by'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_index(op.f('uq_paper_version_no'), 'paper_version', ['paper_id', 'version_no'], unique=True)
    op.create_index(op.f('idx_version_paper'), 'paper_version', ['paper_id'], unique=False)
    op.alter_column('paper_version', 'is_final',
               existing_type=mysql.TINYINT(),
               comment='是否标记为最终版本',
               existing_comment='是否最终版本',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('paper_version', 'version_no',
               existing_type=mysql.INTEGER(),
               comment='版本序号(1开始递增)',
               existing_comment='版本号',
               existing_nullable=False)
    op.alter_column('paper_version', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('paper_version', 'uploaded_at')
    op.drop_column('paper_version', 'comment')
    op.drop_column('paper_version', 'file_hash')
    op.drop_column('paper_version', 'storage_url')
    op.add_column('paper_attachment', sa.Column('paper_version_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='论文版本ID'))
    op.add_column('paper_attachment', sa.Column('file_name', mysql.VARCHAR(length=255), nullable=False, comment='原始文件名'))
    op.add_column('paper_attachment', sa.Column('mime_type', mysql.VARCHAR(length=128), nullable=False, comment='MIME类型'))
    op.add_column('paper_attachment', sa.Column('uploaded_by', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=False, comment='上传人ID'))
    op.create_table_comment(
        'paper_attachment',
        '论文版本附件',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'paper_attachment', type_='foreignkey')
    op.create_foreign_key(op.f('fk_att_uploader'), 'paper_attachment', 'user', ['uploaded_by'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_att_version'), 'paper_attachment', 'paper_version', ['paper_version_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_index(op.f('idx_att_version'), 'paper_attachment', ['paper_version_id'], unique=False)
    op.alter_column('paper_attachment', 'file_hash',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=128),
               nullable=True,
               comment='文件哈希(SHA256)',
               existing_comment='文件哈希值')
    op.alter_column('paper_attachment', 'file_size',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(unsigned=True),
               comment='文件大小字节',
               existing_comment='文件大小(字节)',
               existing_nullable=False)
    op.alter_column('paper_attachment', 'storage_url',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=1024),
               comment='存储地址/URL',
               existing_comment='存储路径',
               existing_nullable=False)
    op.alter_column('paper_attachment', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('paper_attachment', 'attachment_type')
    op.drop_column('paper_attachment', 'filename')
    op.drop_column('paper_attachment', 'paper_id')
    op.add_column('paper', sa.Column('academic_year', mysql.VARCHAR(length=16), nullable=False, comment='学年'))
    op.add_column('paper', sa.Column('keywords', mysql.VARCHAR(length=255), nullable=True, comment='关键词'))
    op.add_column('paper', sa.Column('abstract', mysql.TEXT(), nullable=True, comment='摘要'))
    op.add_column('paper', sa.Column('term', mysql.TINYINT(), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='学期'))
    op.add_column('paper', sa.Column('archived_at', mysql.DATETIME(fsp=3), nullable=True, comment='归档时间'))
    op.add_column('paper', sa.Column('submitted_at', mysql.DATETIME(fsp=3), nullable=True, comment='首次提交时间'))
    op.create_table_comment(
        'paper',
        '论文',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'paper', type_='foreignkey')
    op.drop_constraint(None, 'paper', type_='foreignkey')
    op.create_foreign_key(op.f('fk_paper_student'), 'paper', 'user', ['student_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_paper_topic'), 'paper', 'topic', ['topic_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.create_index(op.f('uq_paper_student_term'), 'paper', ['student_id', 'academic_year', 'term'], unique=True)
    op.create_index(op.f('idx_paper_topic'), 'paper', ['topic_id'], unique=False)
    op.create_index(op.f('idx_paper_status'), 'paper', ['status'], unique=False)
    op.alter_column('paper', 'status',
               existing_type=sa.String(length=16),
               type_=mysql.TINYINT(),
               comment='0=编辑中,1=已提交,2=评审中,3=待修改,4=通过,5=归档',
               existing_comment='状态: DRAFT/SUBMITTED/REVIEWED/APPROVED/REJECTED',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('paper', 'student_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='学生用户ID',
               existing_comment='学生ID',
               existing_nullable=False)
    op.alter_column('paper', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.add_column('operation_log', sa.Column('ip', mysql.VARCHAR(length=64), nullable=True, comment='来源IP'))
    op.add_column('operation_log', sa.Column('actor_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True, comment='操作人ID'))
    op.add_column('operation_log', sa.Column('target_id', mysql.BIGINT(unsigned=True), autoincrement=False, nullable=True, comment='目标记录ID'))
    op.add_column('operation_log', sa.Column('target_table', mysql.VARCHAR(length=64), nullable=True, comment='目标表名'))
    op.create_table_comment(
        'operation_log',
        '操作日志',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'operation_log', type_='foreignkey')
    op.create_foreign_key(op.f('fk_log_actor'), 'operation_log', 'user', ['actor_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    op.create_index(op.f('idx_log_actor'), 'operation_log', ['actor_id', 'created_at'], unique=False)
    op.alter_column('operation_log', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3)'))
    op.alter_column('operation_log', 'detail',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               comment='详情(JSON)',
               existing_comment='操作详情JSON',
               existing_nullable=True)
    op.alter_column('operation_log', 'action',
               existing_type=mysql.VARCHAR(length=64),
               comment='动作标识',
               existing_comment='操作类型: CREATE/UPDATE/DELETE',
               existing_nullable=False)
    op.alter_column('operation_log', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('operation_log', 'ip_address')
    op.drop_column('operation_log', 'resource_id')
    op.drop_column('operation_log', 'resource_type')
    op.drop_column('operation_log', 'user_id')
    op.create_table_comment(
        'major',
        '专业',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'major', type_='foreignkey')
    op.create_foreign_key(op.f('fk_major_department'), 'major', 'department', ['department_id'], ['id'], onupdate='RESTRICT', ondelete='RESTRICT')
    op.alter_column('major', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'))
    op.alter_column('major', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3)'))
    op.alter_column('major', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               comment='1=启用,0=停用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('major', 'name',
               existing_type=mysql.VARCHAR(length=128),
               comment='专业名称',
               existing_nullable=False)
    op.alter_column('major', 'major_code',
               existing_type=mysql.VARCHAR(length=32),
               comment='专业编码',
               existing_nullable=False)
    op.alter_column('major', 'department_id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='所属系部ID',
               existing_nullable=False)
    op.alter_column('major', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'department',
        '系部',
        existing_comment=None,
        schema=None
    )
    op.alter_column('department', 'updated_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)'))
    op.alter_column('department', 'created_at',
               existing_type=mysql.DATETIME(fsp=3),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP(3)'))
    op.alter_column('department', 'status',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(),
               comment='1=启用,0=停用',
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('department', 'name',
               existing_type=mysql.VARCHAR(length=128),
               comment='系部名称',
               existing_nullable=False)
    op.alter_column('department', 'dept_code',
               existing_type=mysql.VARCHAR(length=32),
               comment='系部编码',
               existing_nullable=False)
    op.alter_column('department', 'id',
               existing_type=mysql.BIGINT(unsigned=True),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
